name: Landing Zone 

on: push

jobs:
  terraforminit:
    name: Terraform
    runs-on: [self-hosted, mera-own-label]
    steps:
    - name: workarea directory
      run: echo check for workarea directory 
